# Generated by Django 4.2.29 on 2026-03-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='썸네일'),
        ),
    ]
